version: "3"

services:
  db:
    image: mysql:8
    container_name: studenthelp
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql
      MYSQL_USER: studenthelp
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    network_mode: bridge