# Generated by Django 5.0.3 on 2024-03-30 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1', 'Ouvrier'), ('2', 'Technicien'), ('3', 'PFE')], max_length=80)),
                ('societe', models.CharField(max_length=100)),
                ('duration', models.DurationField()),
                ('sujet', models.CharField(max_length=100)),
                ('contactinfo', models.CharField(max_length=80)),
                ('specialite', models.CharField(max_length=100)),
            ],
        ),
    ]
