# Generated by Django 5.0.3 on 2024-03-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localisation', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('contactinfo', models.CharField(max_length=100)),
            ],
        ),
    ]
