# Generated by Django 5.0.3 on 2024-03-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('heure_depart', models.TimeField()),
                ('nbre_siege', models.IntegerField()),
                ('contactinfo', models.CharField(max_length=100)),
            ],
        ),
    ]
